core/urls.py
from django.contrib import admin
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),

]

list/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'list'

urlpatterns = [
    path('<int:pk>/get/', views.ListGetLinks.as_view(), name='get_links'),
    path('<uuid:pk>/edit/', views.ListEditLinks.as_view(), name='edit_link'),
    path('<uuid:pk>/delete/', views.ListDeleteLink.as_view(), name='delete_link'),

    path('save/', views.ListSaveLinks.as_view(), name='save_links'),
    path('create/', views.ListCreateLink.as_view(), name='create_link'),
    path('<int:pk>/show/', views.ListShowLinks.as_view(), name='show_links_tab'),

    
]

social_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
    path('users/', include('users.urls', namespace='users')),
    path('list/', include('list.urls', namespace='list')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.page_not_found_view"

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UsersRegisterUser.as_view(), name='user_register'),

    path('activate/<uidb64>/<token>/', views.UsersActivateUser.as_view(), name='user_activate'),
    path('forgot/', views.UsersForgotPassword.as_view(), name='forgot_password'),
    path('reset/<uidb64>/<token>/', views.UsersResetPassword.as_view(), name='reset_password'),

    path('search', views.UsersSearch.as_view(), name='search'),

    path('<int:pk>/', views.UsersViewProfile.as_view(), name='view_profile'),
    path('<int:pk>/edit/', views.edit_profile, name='edit_profile'),
    path('<int:pk>/get/', views.get_profile, name='get_profile'),
    path('<int:pk>/change_password/', views.change_password, name='change_password'),

    path('<int:pk>/short_bio/', views.UsersViewShortIntro.as_view(), name='view_short_intro'),
    path('<int:pk>/short_bio/edit', views.UsersEditShortIntro.as_view(), name='edit_short_intro'),
    
    path("qrcode/download", views.DownloadQRCode.as_view(), name='download_qrcode'),
    
]
""" path('users/', views.UsersViewAll.as_view(), name='users'),
    path('users/<int:pk>/', views.UsersViewUser.as_view(), name='user_view'),
    path('users/edit/<int:pk>/', views.UsersEditUser.as_view(), name='user_edit'),
    path('users/delete/<int:pk>/', views.UsersDeleteUser.as_view(), name='user_delete'),
    path('users/create/', views.UsersCreateUser.as_view(), name='user_create'),
    path('users/invite/', views.UsersInviteUser.as_view(), name='user_invite'),
    path('users/reset-password/<int:pk>/', views.UsersResetPassword.as_view(), name='user_reset_password'),
    path('users/create-password/<uuid:uuid>/', views.UsersCreatePassword.as_view(), name='user_create_password'),
    path('profile/<int:pk>/', views.ProfileViewProfile.as_view(), name='view_profile'),
    path('users/register/', views.UsersRegisterUser.as_view(), name='user_register'), """

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.conf import settings

from phonenumber_field.modelfields import PhoneNumberField

#from core.utils import email_user
from core.tasks import email_user

import uuid

from core.storage_backends import PublicMediaStorage

# Create your models here.
class User(AbstractUser):
   
   phone_number = PhoneNumberField(blank = True, region='US')

   def send_activation(self):

      html = render_to_string('emails/activate_user.html', {
         'user': self.first_name,
         'domain': settings.APP_URL,
         'app_name': settings.APP_NAME,
         'uid': urlsafe_base64_encode(force_bytes(self.id)),
         'token': default_token_generator.make_token(self),
      })
      
      response = email_user.delay(self.email, html, subject="Activate account")

   def send_password_reset(self):
      
      html = render_to_string('emails/reset_password.html', {
         'user': self.first_name,
         'domain': settings.APP_URL,
         'app_name': settings.APP_NAME,
         'uid': urlsafe_base64_encode(force_bytes(self.id)),
         'token': default_token_generator.make_token(self),
      })
      
      response = email_user.delay(self.email, html, subject='Reset Password')
      

class UserProfile(models.Model):
   id = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True, editable=False)
   short_intro = models.CharField(max_length=25, blank=True, null=True)
   bio = models.TextField(blank=True, null=True)
   profile_image = models.ImageField(blank=False, storage=PublicMediaStorage(), upload_to='profiles/', default="profiles/user-default.png")
   user = models.OneToOneField(User, related_name="user_profile", on_delete=models.CASCADE, null=True, blank=True)
   def __str__(self):
        return str(self.user.username)

   @property
   def imageURL(self):
      try:
         url = self.profile_image.url
      except:
         url = ''
      return url

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import User, UserProfile

class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name','email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        
        super(RegisterUserForm, self).__init__(*args,**kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
  
class UserModelForm(ModelForm):
    class Meta:
        model = User
        fields = [ 'first_name', 'last_name', 'email', 'phone_number' ]

    def __init__(self, *args, **kwargs):
        
        super(UserModelForm, self).__init__(*args,**kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
        
class UserProfileModelForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = [ 'profile_image', 'bio' ]

    def __init__(self, *args, **kwargs):
        
        super(UserProfileModelForm, self).__init__(*args,**kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

users/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.contrib import messages
from django.conf import settings
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.password_validation import validate_password
from django.http import Http404, HttpResponse
from django.urls import reverse
from django.db.models import Q

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from list.forms import LinkModelForm
from list.models import Link
from core.utils import generate_qr_code
from .forms import RegisterUserForm, UserModelForm, UserProfileModelForm
from .models import User
from .utils import paginate_users

# Create your views here.
class UsersRegisterUser(View):
    def get(self,request):
        form = RegisterUserForm()
        context = {
           'next': 'core:index',
           'form': form
        }
        #return render(request, 'signup.html', context)
        return render( request, 'registration/signup.html', context)


    def post(self, request):
        print(request.POST)
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            print('Checking User...')
            username = form.cleaned_data['username']
            found = True
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                found = False    

            if found == True:
                messages.error(request,'Username already exists.')
                context = {
                    'next': 'core:index',
                    'form': form
                }
                    
                return render( request, 'registration/signup.html', context)

            password = form.cleaned_data['password1']
            password_hash = make_password(password)
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            user = User(username=username,password=password_hash,first_name=first_name,last_name=last_name,email=email,is_staff=False,is_active=False,is_superuser=False)
            user.save()
            user.send_activation()
            messages.success(request, "User activation email has been sent.")
            #messages.success(request, "Your account has been created.")
        else:
            messages.error(request,'Error in form validation.')
            context = {
                'next': 'core:index',
                'form': form
            }
                
            return render( request, 'registration/signup.html', context)
        return redirect('core:index')
            
        
class UsersActivateUser(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(id = uid)
        except:
            user = None
        
        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Your account has been activated.')
            return redirect('core:index')
        else:
            messages.error(request, 'Invalid activation link.')
            return redirect('core:index')

class UsersResetPassword(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(id = uid)
        except:
            user = None
        
        if user is not None and default_token_generator.check_token(user, token):
            context = {
               'user': user,
               'next': 'core:index',
               'uidb64': uidb64, 
               'token': token
            }
            return render(request, 'users/reset_password.html', context)
        else:
            messages.error(request, 'Invalid link.')
            return redirect('core:index')
        
    def post(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(id = uid)
        except:
            messages.error(request, 'Error setting new password.')
            return redirect('users:reset_password', uidb64=request.POST['uidb64'], token=request.POST['token'])
        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            password = request.POST['new_password']
            confirm_password = request.POST['confirm_password']
            if password != confirm_password:
                messages.error(request, 'Your passwords do not match.')
                return redirect('users:reset_password', uidb64=request.POST['uidb64'], token=request.POST['token'])
            password_hash = make_password(password)
            user.password = password_hash
            user.save()
            messages.success(request, 'Your password has been reset.')
            return redirect('core:index')
        else:
            messages.error(request, 'Error setting new password.')
            return redirect('users:reset_password', uidb64=request.POST['uidb64'], token=request.POST['token'])
class UsersForgotPassword(View):
    def get(self, request):
        context = {
            'next': 'core:index'
        }
        return render(request, 'users/forgot_password.html', context)
    def post(self, request):
        email = request.POST['email']
        try:
            user = User.objects.get(email=email)
          
            user.is_active = False
           
            user.save()           
            user.send_password_reset()
            
        except:
            pass

        messages.info(request, "An email has been sent.  If you don't receive the link, check your SPAM folder or verify the email address and try again.")    

        return redirect('core:index')

class UsersSearch(View):
    def get(self, request):
        print(request.GET)

        search_query = ''

        search_query = request.GET.get('search_query', '')

        links = Link.objects.filter(Q(type__icontains=search_query) | Q(link__icontains=search_query))
        users = User.objects.distinct().filter(Q(is_superuser=False)&(Q(username__icontains=search_query) | Q(first_name__icontains=search_query) | Q(last_name__icontains=search_query) | 
                                                          Q(email__icontains=search_query) | Q(link__in=links) |
                                                          Q(user_profile__short_intro__icontains=search_query) |
                                                          Q(user_profile__bio__icontains=search_query))).defer('password')
        
        custom_range, users = paginate_users(request, users, 10)
        context = {
            'users': users,
            'custom_range': custom_range,
            'search_query': search_query
        }
        return render(request, 'users/search.html', context)
    
class UsersViewProfile(View):
    def get(self, request, pk):
        try:
            user = User.objects.get(id=pk)
        except:
            messages.error(request, "Cannot load profile.")
            return redirect('core:index')
        links = []
        profile_link = f'http://{settings.APP_URL}/users/{user.id}'
        stream = generate_qr_code(profile_link)
        context = {
            'user': user,
            'links': links,
            'profile_link': profile_link,
            'qrcode': stream.getvalue().decode()
        }
        return render(request, 'users/profile.html', context)

class UsersViewShortIntro(View):
    def get(self, request, pk):
        if request.htmx == False:
            return Http404
        try:
            user = User.objects.get(id=pk)
        except:
            user = None
        context = {
            'user': user
        }
        return render(request, 'users/partials/short_intro.html', context)

class UsersEditShortIntro(LoginRequiredMixin, View):
    def get(self, request, pk):
        if request.htmx == False:
            return Http404
        try:
            user = User.objects.get(id=pk)
        except:
            user = None
        context = {
            'user': user
        }
        return render(request, 'users/partials/update_intro.html', context)
    def post(self, request, pk):
        if request.htmx == False:
            return Http404
        try:
            user = User.objects.get(id=pk)
        except:
            user = None
        if request.user.id == user.id:
            short_intro = request.POST['short_intro']
            user.user_profile.short_intro = short_intro
            user.user_profile.save()

        context = {
            'user': user
        }
        return render(request, 'users/partials/short_intro.html', context)

class DownloadQRCode(View):
    def get(self, request):
        
        url = request.GET.get('url')
            
        stream = generate_qr_code(url)

        headers = {
                'Content-Type': 'image/svg+xml',
                'Content-Disposition': 'inline; filename="qrcode.svg"'
            }
            
        return HttpResponse(stream.getvalue().decode(), headers=headers)

#@login_required(login_url='login')
def get_profile(request, pk):
    if request.htmx == False:
        return Http404
    try:
        user = User.objects.get(id= pk)
        links = list(Link.objects.filter(user=user).values('type','link'))
    except:
        messages.error(request, "Cannot load profile.")
        return redirect('core:index')
    for link in links:
        temp_link = Link(type=link['type'])
        link['label'] = temp_link.get_type_display()

    
    context = {

users/templates/users/partials/short_intro.html
<h3>{{ user.user_profile.short_intro}} {% if user.id == request.user.id %}<span hx-get="{% url 'users:edit_short_intro' user.id %}" hx-trigger="click" hx-target="#short_intro" hx-swap="innerHTML"><i class="fa-solid fa-pencil"></i></span> {% endif %}</h3>

users/templates/users/partials/tab.html
<ul class="nav nav-tabs nav-tabs-bordered">

<li class="nav-item">
    <a hx-get="{% url 'users:get_profile' user.id %}" hx-trigger="click" hx-target="#tabs" hx-swap="innerHTML" class="nav-link {% if tab == 1 %}active{% endif%}" >Overview</a>
</li>

{% if request.user.id == user.id %}
<li class="nav-item ">
    <a hx-get="{% url 'users:edit_profile' user.id %}" hx-trigger="click" hx-target="#tabs" hx-swap="innerHTML" class="nav-link {% if tab == 2 %}active{% endif%}" >Edit Profile</a>
</li>

<li class="nav-item ">
    <a hx-get="{% url 'list:show_links_tab' user.id %}" hx-trigger="click" hx-target="#tabs" hx-swap="innerHTML" class="nav-link {% if tab == 3 %}active{% endif%}" >Manage Links</a>
</li>

<li class="nav-item ">
    <a hx-get="{% url 'users:change_password' user.id %}" hx-trigger="click" hx-target="#tabs" hx-swap="innerHTML" class="nav-link {% if tab == 99 %}active{% endif%}" >Change Password</a>
</li>
{% endif %}
</ul>

 <div class="tab-content pt-2">
    {% include 'partials/messages.html' %}
                {% if tab == 1 %}
                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                  <h5 class="card-title">About</h5>
                  <p class="small fst-italic">{{ user.user_profile.bio }}</p>

                  <h5 class="card-title">Profile Details</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Full Name</div>
                    <div class="col-lg-9 col-md-8">{{user.first_name}} {{user.last_name}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Phone</div>
                    <div class="col-lg-9 col-md-8">{{ user.phone_number.as_national }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Email</div>
                    <div class="col-lg-9 col-md-8">{{ user.email }}</div>
                  </div>
                <h5 class="card-title">Links</h5>
                  {% include 'list/partials/links.html' %}

                </div>
                {% endif %}
                {% if request.user.id == user.id %}
                {% if tab == 2 %}
                <div class="tab-pane fade show active profile-edit" id="profile-edit">

                  <!-- Profile Edit Form -->
                  <form hx-post="{% url 'users:edit_profile' user.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in user_form %}
                    <div class="row mb-3">
                        {{ field.label }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}

                    {% for field in profile_form %}
                    <div class="row mb-3">
                        {{ field.label }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                      <a hx-get="{% url 'users:get_profile' user.id %}" hx-trigger="click" hx-target="#tabs" hx-swap="innerHTML" class="btn btn-danger">Cancel</a>
                    </div>
                  </form><!-- End Profile Edit Form -->

                </div>
                {% endif %}

                {% if tab == 3 %}
                <div class="tab-pane fade show active profile-edit" id="links-edit" >
                  <div id="links-list" hx-get="{% url 'list:get_links' user.id %}" hx-trigger="load" hx-target="#links-list" hx-swap="innerHTML"></div>

                </div>
                {% endif %}

                {% if tab == 99%}
                <div class="tab-pane fade show active pt-3" id="profile-change-password">
                  <!-- Change Password Form -->
                  <form hx-post="{% url 'users:change_password' user.id %}" >
                    {% csrf_token %}
                    
                    <div class="row mb-3">
                      <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="password" type="password" class="form-control" id="currentPassword">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="new_password" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="new_password" type="password" class="form-control" id="new_password">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="confirm_password" class="col-md-4 col-lg-3 col-form-label">Confirm Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="confirm_password" type="password" class="form-control" id="confirm_password">
                      </div>
                    </div>

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Change Password</button>
                    </div>
                  </form><!-- End Change Password Form -->

                </div>
                {% endif %}
                {% endif %}
</div><!-- End Bordered Tabs -->

users/templates/users/partials/update_intro.html
<form hx-post="{% url 'users:edit_short_intro' user.id %}" hx-target="#short_intro">
    {% csrf_token %}
    <input type="text" name="short_intro" class="form-control" id="short_intro" value="{{ user.user_profile.short_intro }} " >
    <br>
    <button class="btn btn-sm btn-primary" type="submit">Save</button>
</form>

users/templates/users/partials/users.html
 {% for user in users %}
 <div class="col-xl-12">
    <div class="row">
          
        <div class="card">
              <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                 
                <img src="{{user.user_profile.profile_image.url}}"  alt="Profile" class="rounded-circle">
                <a href="{% url 'users:view_profile' user.id %}"><h2>{{ user.first_name }} {{ user.last_name}}</h2></a>
                <h3>{{ user.user_profile.short_intro}} </h3>
                
                <div class="post-item clearfix">
                  <p>{{ user.user_profile.bio|slice:'100'}}</p>
                </div>
              </div>
        </div>
        
    </div>
     
</div>
{% endfor %}