core/urls.py
from django.contrib import admin
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),

]

social_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
    path('users/', include('users.urls', namespace='users')),
    path('list/', include('list.urls', namespace='list')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.page_not_found_view"

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UsersRegisterUser.as_view(), name='user_register'),

    path('activate/<uidb64>/<token>/', views.UsersActivateUser.as_view(), name='user_activate'),
    path('forgot/', views.UsersForgotPassword.as_view(), name='forgot_password'),
    path('reset/<uidb64>/<token>/', views.UsersResetPassword.as_view(), name='reset_password'),

    path('search', views.UsersSearch.as_view(), name='search'),

    path('<int:pk>/', views.UsersViewProfile.as_view(), name='view_profile'),
    path('<int:pk>/edit/', views.edit_profile, name='edit_profile'),
    path('<int:pk>/get/', views.get_profile, name='get_profile'),
    path('<int:pk>/change_password/', views.change_password, name='change_password'),

    path('<int:pk>/short_bio/', views.UsersViewShortIntro.as_view(), name='view_short_intro'),
    path('<int:pk>/short_bio/edit', views.UsersEditShortIntro.as_view(), name='edit_short_intro'),
    
    path("qrcode/download", views.DownloadQRCode.as_view(), name='download_qrcode'),
    
]
""" path('users/', views.UsersViewAll.as_view(), name='users'),
    path('users/<int:pk>/', views.UsersViewUser.as_view(), name='user_view'),
    path('users/edit/<int:pk>/', views.UsersEditUser.as_view(), name='user_edit'),
    path('users/delete/<int:pk>/', views.UsersDeleteUser.as_view(), name='user_delete'),
    path('users/create/', views.UsersCreateUser.as_view(), name='user_create'),
    path('users/invite/', views.UsersInviteUser.as_view(), name='user_invite'),
    path('users/reset-password/<int:pk>/', views.UsersResetPassword.as_view(), name='user_reset_password'),
    path('users/create-password/<uuid:uuid>/', views.UsersCreatePassword.as_view(), name='user_create_password'),
    path('profile/<int:pk>/', views.ProfileViewProfile.as_view(), name='view_profile'),
    path('users/register/', views.UsersRegisterUser.as_view(), name='user_register'), """

templates/footer.html
{% load static i18n %}
{% load django_htmx %}

<footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

       
        <script>
                document.body.addEventListener('htmx:configRequest', (event) => {
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'; })
        </script>
</body>

</html> 

templates/head.html
{% load static i18n %}
{% load django_htmx %}

<!DOCTYPE html>  
<html lang="en"> 
<head>  
     <!-- Required meta tags -->
     <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{{ settings.APP_NAME }}</title>  
    <style>
        [x-cloak] { display: none !important; }
    </style>
    <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css'  %}" rel="stylesheet">
    {% comment %} <script src="https://kit.fontawesome.com/11129ed0f0.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% endcomment %}
    <script src="https://kit.fontawesome.com/11129ed0f0.js" crossorigin="anonymous"></script> 
    <script src="https://unpkg.com/htmx.org@1.9.0" integrity="sha384-aOxz9UdWG0yBiyrTwPeMibmaoq07/d3a96GCbb9x60f3mOt5zwkjdbcHFnKH8qls" crossorigin="anonymous"></script>
    {% django_htmx_script %}
    <script defer src="https://unpkg.com/alpinejs@3.10.2/dist/cdn.min.js"></script>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>  
<body class="toggle-sidebar"> 

templates/main.html
{% load static i18n %}
{% load django_htmx %}

{% include 'head.html' %}

        
{% block navbar %}{% endblock %}
{% if user.is_authenticated %}
{% comment %} {% include 'sidebar.html' %} {% endcomment %}
{% endif %}
<main id="main" class="main">
              
       

    <section class="section">
     {% include 'partials/messages.html' %}
      <div class="row justify-content-center">
        <div class="col-lg-10">

          <div class="card">
            <div class="card-body">
              
                {% block content %}{% endblock %}
          
            </div>
          </div>

        </div>

     
      </div>
    </section>

  </main><!-- End #main -->
       
        <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
 

templates/navbar copy 2.html
{% extends "main.html" %}
{% load static %}
{% block navbar %}
<!--Navbar-->

<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <img src="{% static '/img/logo.png' %}" alt="">
        <span class="d-none d-lg-block">NiceAdmin</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-bell"></i>
            <span class="badge bg-primary badge-number">4</span>
          </a><!-- End Notification Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
            <li class="dropdown-header">
              You have 4 new notifications
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-exclamation-circle text-warning"></i>
              <div>
                <h4>Lorem Ipsum</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>30 min. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-x-circle text-danger"></i>
              <div>
                <h4>Atque rerum nesciunt</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>1 hr. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-check-circle text-success"></i>
              <div>
                <h4>Sit rerum fuga</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>2 hrs. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-info-circle text-primary"></i>
              <div>
                <h4>Dicta reprehenderit</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>4 hrs. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>
            <li class="dropdown-footer">
              <a href="#">Show all notifications</a>
            </li>

          </ul><!-- End Notification Dropdown Items -->

        </li><!-- End Notification Nav -->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-success badge-number">3</span>
          </a><!-- End Messages Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
            <li class="dropdown-header">
              You have 3 new messages
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="#">
                <img src="{% static 'img/messages-1.jpg' %}" alt="" class="rounded-circle">
                <div>
                  <h4>Maria Hudson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>4 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="#">
                <img src="{% static 'img/messages-2.jpg' %}" alt="" class="rounded-circle">
                <div>
                  <h4>Anna Nelson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>6 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="#">
                <img src="{% static 'img/messages-3.jpg' %}" alt="" class="rounded-circle">
                <div>
                  <h4>David Muldon</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>8 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="dropdown-footer">
              <a href="#">Show all messages</a>
            </li>

          </ul><!-- End Messages Dropdown Items -->

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{% static '/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Kevin Anderson</h6>
              <span>Web Designer</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                <i class="bi bi-question-circle"></i>
                <span>Need Help?</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->
 
{% endblock %}

templates/navbar copy.html
{% extends "main.html" %}
{% load static %}
{% block navbar %}
<!--Navbar-->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'core:index' %}">{{ settings.APP_NAME }}</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
    
      {% comment %} {% url 'leader_board:leaders' as leader_url %}
      <li class ="nav-item">
          <a class="nav-link {% if request.get_full_path == leader_url %} active {% endif%}" {% if request.get_full_path == leader_url %} aria-current="page"  {% endif %} href="{% url 'leader_board:leaders' %}">Leader Board</a></li>
      </li>
    
      {% if user.is_authenticated and user.is_staff %}
      {% url 'users:users' as users_url %}
      <li class ="nav-item">
          <a class="nav-link {% if request.get_full_path == users_url %} active {% endif%}" {% if request.get_full_path == users_url %} aria-current="page"  {% endif %} href="{% url 'users:users' %}">Users</a></li>
      </li>
      {% url 'maintenance:update' as maintenance_url %}
      <li class ="nav-item">
          <a class="nav-link {% if request.get_full_path == maintenance_url %} active {% endif%}" {% if request.get_full_path == maintenance_url %} aria-current="page"  {% endif %} href="{% url 'maintenance:update' %}">Maintenance</a></li>
      </li>
      {% endif %}
      {% if user.is_authenticated %}
  
      {% endif %} {% endcomment %}

    </ul>
    

    <div class="navbar-collapse justify-content-end " id="navbarNavDarkDropdown">
      {% if user.is_authenticated and user.tenant != None %}
        <ul class="navbar-nav">
            
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Tenants
            </a>
            <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
              {% for tenant in user.tenant.all %}
              <li class ="nav-item">
                <a class="dropdown-item" href="{% url 'tenant:tenant_redirect' tenant.id %}">{{tenant.name}}</a>
              </li>
              {% endfor %}
            
            </ul>
          </li>
    
        </ul>
      {% endif %}
      <ul class="navbar-nav">
        {% if  user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
             
              <li class ="nav-item">
                <a class="dropdown-item" href="{% url 'logout' %}?next={% url 'core:index' %}">Logout</a>
              </li>
            
            </ul>
          </li>
        {% else %}
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'login' %}?next={% url 'core:index' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>


</nav>

 
{% endblock %}

templates/navbar.html
{% extends "main.html" %}
{% load static %}
{% block navbar %}
<!--Navbar-->

<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'core:index' %}" class="logo d-flex align-items-center">
        <img src="{% static 'img/logo.png' %}" alt="">
        <span class="d-none d-lg-block">{{settings.APP_NAME}}</span>
      </a>
      {% comment %} 
      {% if user.is_authenticated %}
      <i class="bi bi-list toggle-sidebar-btn"></i>
      {% endif %} {% endcomment %}
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="GET" action="{% url 'users:search' %}">
        
        <input type="text" name="search_query" placeholder="Search" value="{{search_query}}" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        

        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown pe-3">
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{{  request.user.user_profile.profile_image.url }}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{ request.user.first_name|slice:'1' }}. {{ request.user.last_name}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{ request.user.first_name }} {{ request.user.last_name}}</h6>
              <span>{{request.user.user_profile.short_intro}}</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'users:view_profile' request.user.id %}">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
        
            <li>
              <hr class="dropdown-divider">
            </li>            
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}?next={% url 'core:index' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->
        {% else %}
         <li class ="nav-item pe-3">
            <a class="nav-link" href="{% url 'users:user_register' %}?next={% url 'core:index' %}">Register</a>
          </li>
        <li class ="nav-item pe-3">
            <a class="nav-link" href="{% url 'login' %}?next={% url 'core:index' %}">Login</a>
        </li>
        
        {% endif %}

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->
 
{% endblock %}