core/urls.py
from django.contrib import admin
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),

]

list/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'list'

urlpatterns = [
    path('<int:pk>/get/', views.ListGetLinks.as_view(), name='get_links'),
    path('<uuid:pk>/edit/', views.ListEditLinks.as_view(), name='edit_link'),
    path('<uuid:pk>/delete/', views.ListDeleteLink.as_view(), name='delete_link'),

    path('save/', views.ListSaveLinks.as_view(), name='save_links'),
    path('create/', views.ListCreateLink.as_view(), name='create_link'),
    path('<int:pk>/show/', views.ListShowLinks.as_view(), name='show_links_tab'),

    
]

social_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
    path('users/', include('users.urls', namespace='users')),
    path('list/', include('list.urls', namespace='list')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.page_not_found_view"

list/models.py
from django.db import models

import uuid

from users.models import User

# Create your models here.
class Link(models.Model):
    SOCIAL_LINKS = (
        ('facebook', 'Facebook'),
        ('twitter', 'Twitter'),
        ('instagram', 'Instagram'),
        ('tiktok', 'TikTok'),
        ('linkedin', 'LinkedIn'),
        ('github', 'GitHub'),
        ('discord', 'Discord'),
        ('youtube', 'YouTube'),
        ('medium', 'Medium'),
        ('telegram', 'Telegram'),
        ('etsy', 'Etsy'),
        ('twitch', 'Twitch'),
        ('reddit', 'Reddit'),
        ('patreon', 'Patreon'),
        ('flickr', 'Flickr'),
        ('other', 'Other'),

    )

    id = models.UUIDField(primary_key=True, editable=False,default=uuid.uuid4)
    handle = models.CharField(max_length=100,null=False, blank=False)
    link = models.CharField(max_length=200,blank=True,null=True)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    type = models.CharField(choices=SOCIAL_LINKS,max_length=100)

    def __str__(self):
        return self.user.username + " - " + self.link
    

list/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Link

  
class LinkModelForm(ModelForm):
    class Meta:
        model = Link
        fields = [ 'type', 'link',  ]

    def __init__(self, *args, **kwargs):
        
        super(LinkModelForm, self).__init__(*args,**kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
 

list/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.contrib import messages
from django.conf import settings
from django.http import Http404
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from users.models import User

from .models import Link
from .forms import LinkModelForm

# Create your views here.
class ListShowLinks(LoginRequiredMixin, View):
    def get(self, request, pk):
        if request.htmx == False:
            return Http404
        try:
            user = User.objects.get(id= pk)
            
        except:
            messages.error(request, "Cannot load links.")
        context = {
            'user': user,
            
            'tab': 3
        }
        return render(request, 'users/partials/tab.html', context)

class ListGetLinks(LoginRequiredMixin, View):
    def get(self, request, pk):
        if request.htmx == False:
            return Http404
        try:
            user = User.objects.get(id= pk)
            links = list(Link.objects.filter(user=user).values('type','link','id'))
            
        except:
            messages.error(request, "Cannot load links.")
            links = []
        for link in links:
            temp_link = Link(type=link['type'])
            link['label'] = temp_link.get_type_display()
        context = {
            'user': user,
            'links': links,
            
        }
        return render(request, 'list/partials/manage_links.html', context)
class ListEditLinks(LoginRequiredMixin, View):
    def get(self, request,pk):
        if request.htmx == False:
            return Http404
        try:
           
            link = Link.objects.get(id=pk, user=request.user)
            
            form = LinkModelForm(instance=link)

        except:
            messages.error(request, "Cannot load links.")
            link = []
        context = {
            'link_form': form,
            'link': link
           
        }
        
        return render(request, 'list/partials/link_form.html', context)
class ListDeleteLink(LoginRequiredMixin, View):
    def delete(self, request, pk):
        if request.htmx == False:
            return Http404
        
        try:
            link = Link.objects.get(id=pk)
            link.delete()
        except:
            print("error deleting link")

        try:
            #user = User.objects.get(id= pk)
            links = list(Link.objects.filter(user=request.user).values('type','link','id'))
            
        except:
            messages.error(request, "Cannot load links.")
            links = []
        for link in links:
            temp_link = Link(type=link['type'])
            link['label'] = temp_link.get_type_display()
        context = {
           
            'links': links,
            
        }
        return render(request, 'list/partials/manage_links.html', context)

class ListCreateLink(LoginRequiredMixin, View):
    def get(self, request):
        form = LinkModelForm()
        context = {
            'link_form': form,
            'link': None
        }
        return render(request, 'list/partials/link_form.html', context)

class ListSaveLinks(LoginRequiredMixin, View):
    def post(self, request):
        if request.htmx == False:
            return Http404
        try:
            print(request.POST)
            pk = request.POST['linkId']
            link_type = request.POST['type']
            link_link = request.POST['link']
            try:
                #link = Link.objects.get(user=request.user,type=link_type,link=link_link)
                link = Link.objects.get(user=request.user,id=pk)
                link_form = LinkModelForm(request.POST, instance=link)

            except:
                link_form = LinkModelForm(request.POST)

            if link_form.is_valid():
                link = link_form.save(commit=False)
                link.user = request.user
                link.save()
            
        except:
            messages.error(request, "Cannot load links.")
        try:
           
            links = list(Link.objects.filter(user=request.user).values('type','link','id'))
            
        except:
            messages.error(request, "Cannot load links.")
            links = []
        for link in links:
            temp_link = Link(type=link['type'])
            link['label'] = temp_link.get_type_display()
        context = {
            'links': links,
            
        }
        return render(request, 'list/partials/manage_links.html', context)
       

list/templates/list/partials/link_form.html
<form class="row g-3 align-middle" hx-post="{% url 'list:save_links' %}">
   
    {% for field in link_form %}
    {% if field.label == 'Type'%}
     <div class="col-md-2 mb-3 align-middle" >
        {{ field.label }}
        {{ field }}
     </div>
     {% else %}
    <div class="col-md-7 mb-3 align-middle" >
        {{ field.label }}
        {{ field }}
     </div>
     
     {% endif %}
     <input type="hidden" id="linkId" name="linkId" value="{{link.id}}">
    {% endfor %}
    
    <div class="col-3  align-self-center">
        <button class="btn btn-primary btn-sm" type="submit">Submit</button>
        {% if link != None %}<a hx-delete="{% url 'list:delete_link' link.id %}" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></a>
        {% else %}
        <a hx-get="{% url 'list:show_links_tab' request.user.id %}" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></a>
        {% endif %}

    </div>
    

</form>
 {% comment %} <div class="col-4  align-self-center">
        <button class="btn btn-success btn-sm"
        hx-get="{% url 'list:create_link' %}"
        hx-target="#links-edit"
        hx-swap="beforeend">+ Add Link</button>
</div> {% endcomment %}
    

list/templates/list/partials/links.html
<ul class="list-group">
{% for link in links %}
    {% comment %} <li class="list-group-item"><i class="fa-brands fa-{{link.type}}"></i> {{link.link}}</li> {% endcomment %}
    <div class="row">
        
        <div class="col-lg-3 col-md-4 label">{% if link.type != 'other' %}
        <i class="fa-brands fa-{{link.type}}"></i>
        {% endif %} {{ link.label }}</div>
        <div class="col-lg-9 col-md-8"><a href="{{ link.link }}" target="_blank"> {{link.link}} </a> </div>
      
    </div>
{% endfor %}                
</ul>
{% comment %} 
                  <div class="row">
                    
                    <div class="col-lg-3 col-md-4 label">{{ link.type }}</div>
                    <div class="col-lg-9 col-md-8">{{ link.link }} </div>
                
                  </div>
 {% endcomment %}

list/templates/list/partials/manage_links.html
<ul class="list-group" id="link-group">
{% for link in links %}
    <div class="row">
        <div class="col-lg-3 col-md-4 label">{% if link.type != 'other' %}
        <i class="fa-brands fa-{{link.type}}"></i>
        {% endif %} {{ link.label }}</div>
        <div class="col-lg-9 col-md-8" id="link">{{ link.link }} <span hx-get="{% url 'list:edit_link' link.id %}" hx-trigger="click" hx-swap="innerHTML"><i class="fa-solid fa-pencil"></i></span></div>
    </div>
{% endfor %}                
</ul>
<br>
 <button class="btn btn-success btn-sm"
        hx-get="{% url 'list:create_link' %}"
        hx-target="#link-group"
        hx-swap="beforeend">+ Add Link</button>